# sealed-secrets/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-sealed-secrets.yaml
  - negocio-sealed-secrets.yaml
  - gateway-sealed-secrets.yaml
  - frontend-sealed-secrets.yaml

namespace: dev