apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LucaCostabile/infrastructura-Atales
    targetRevision: dev-v2
    path: overlays/dev/mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
